# Configuration for welcome - https://github.com/behaviorbot/welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  💖 Thanks for opening this pull request! 💖 Please check out our contributing [guidelines](https://github.com/Verizon-Geeks/cncf-clients/blob/master/CONTRIBUTING.md#your-first-pull-request).

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! 🎉🎉🎉
  
  ![congratulations](https://user-images.githubusercontent.com/26694932/65509582-6b95af80-def0-11e9-8f2b-cd4662f25d28.gif)
