version: 2
mergeable:
  - when: pull_request.*
    validate:
      # list of validators. Specify one or more.
      - do: project
        no_empty:
          enabled: true
          message: 'Assign this to cncf-clients project'
        must_include:
          regex: 'cncf-clients'
          message: 'Assign this to cncf-clients project'
