version: 2
mergeable: #do this for all issues and pull requests
  - when: pull_request.*
    validate:
      # list of validators. Specify one or more.
      - do: project
        no_empty:
          enabled: true
          message: 'Assign this to cncf-clients project'
        begins_with:
          match: 'cncf' # array of strings
          message: 'Assigned to cncf-clients project'
