---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: my-domain-com
  namespace: default
spec:
  secretName: my-domain-com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: 'my.domain.com'
  dnsNames:
  - my.domain.com
  acme:
    config:
    - dns01:
        provider: cf-dns
      domains:
        - my.domain.com