---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: myemail@email.com
    privateKeySecretRef:
      name: letsencrypt
    dns01:
      providers:
      - name: cf-dns
        cloudflare:
          email: myemail@email.com
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key.txt